### ISSUE TITLE
Second machine frontend not working

### ISSUE THREAD

**Issue by bellfeige** [ngocjr7/bcb_vosy#1]
1. Launch services on the first machine (Win10). _Everything goes fine._
2. Run below on 2nd machine (Win10) to connect to 1st machine. _Everything goes fine._
`python bcb_server/peer.py --orderer [first_machine_ip] --ca [first_machine_ip]`
3. Run below to launch frontend on 2nd. _No page loaded_ 
`python vosy_app/vosy.py`

What exactly should I run on 2nd machine to  launch a frontend?

**Comment by ngocbh** [comment]
Because you are using Windows, `0.0.0.0` is not localhost. You should pass localhost IP `127.0.0.1` to connect to the local peer. The complete command is:

```
python vosy_app/vosy.py --host 127.0.0.1
```

**Comment by bellfeige** [comment]
> Because you are using Windows, `0.0.0.0` is not localhost. You should pass localhost IP `127.0.0.1` to connect to the local peer. The complete command is:
> 
> ```
> python vosy_app/vosy.py --host 127.0.0.1
> ```

Works for me, thanks
